version: '3.1'

volumes:
  pg_telegram:

services:
  telegram_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db_telegram
    volumes:
      - pg_telegram:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - telegram_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://telegram_db:5432/db_telegram'
      JAVA_OPTS: '-Xmx512m'
